// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMwPH1C28oVSPK6ADw4nghVUm_1hEHA2U',
    appId: '1:849235045302:web:bd3d6cd02ee67729d86f17',
    messagingSenderId: '849235045302',
    projectId: 'flutterfire-ui-codelab-7315e',
    authDomain: 'flutterfire-ui-codelab-7315e.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-7315e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCO6OJj09dsovaGDIoGOjPdriVdALSZE',
    appId: '1:849235045302:android:1441573781d75a7dd86f17',
    messagingSenderId: '849235045302',
    projectId: 'flutterfire-ui-codelab-7315e',
    storageBucket: 'flutterfire-ui-codelab-7315e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaufTjR5l8As6m7o2neVNsbKvxd6Bz0ys',
    appId: '1:849235045302:ios:1c2ba85a39388058d86f17',
    messagingSenderId: '849235045302',
    projectId: 'flutterfire-ui-codelab-7315e',
    storageBucket: 'flutterfire-ui-codelab-7315e.appspot.com',
    iosClientId: '849235045302-oamm0e9iejd74hcv80jme833681ugno9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaufTjR5l8As6m7o2neVNsbKvxd6Bz0ys',
    appId: '1:849235045302:ios:1c2ba85a39388058d86f17',
    messagingSenderId: '849235045302',
    projectId: 'flutterfire-ui-codelab-7315e',
    storageBucket: 'flutterfire-ui-codelab-7315e.appspot.com',
    iosClientId: '849235045302-oamm0e9iejd74hcv80jme833681ugno9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
